replicaCount: 1

name: springapp
namespace: application

route:
  hostname: application
  gateway:
    name: application-gateway
    namespace: application-gateway

serviceMonitor:
  enabled: false

postgres:
  secret: postgres-secret

logging: INFO
