apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: application
type: Opaque
stringData:
  postgres-db: "spring_jpa"
  postgres-user: "spring_user"
  postgres-password: "change-me-now"
