apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080