{{- if and (eq .Values.database.mode "internal") (not .Values.database.internal.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.internal.secretName }}
type: Opaque
stringData:
  postgres-user: {{ .Values.database.internal.username | quote }}
  postgres-password: "change-me-now"
  postgres-db: {{ .Values.database.internal.dbName | quote }}
{{- end }}
