{{- if and (eq .Values.database.mode "internal") .Values.database.internal.enabled (not .Values.database.internal.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.db.secretName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "postgres.db.usernameKey" . }}: {{ .Values.database.internal.username | quote }}
  {{ include "postgres.db.passwordKey" . }}: {{ .Values.database.internal.password | quote }}
  {{ include "postgres.db.nameKey" . }}: {{ .Values.database.internal.dbName | quote }}
{{- end }}