{{- if and (eq .Values.database.mode "internal") .Values.database.internal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.serviceName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.database.internal.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
{{- end }}