#image:
#  repository: postgres
#  tag: "16.2"
#  pullPolicy: IfNotPresent

#database:
#  resources:
#    requests:
#      cpu: 100m
#      memory: 256Mi
#    limits:
#      cpu: 500m
#      memory: 512Mi

#  internal:
#    enabled: true
#    serviceName: postgres
#    port: 5432
#    dbName: spring_jpa
#    username: spring_user
#    password: change-me-now
#    existingSecret: ""
#    secretName: postgres-secret
#    storageClassName: ""
#    storageSize: 5Gi
#    resources:
#      requests:
#        cpu: 100m
#        memory: 256Mi
#      limits:
#        cpu: 500m
#        memory: 512Mi
#
#  external:
#    host: ""
#    port: 5432
#    dbName: ""
#    existingSecret: ""
#    usernameKey: username
#    passwordKey: password
#    dbNameKey: database