apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-app
  namespace: application
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: {{ .Values.app.springProfilesActive | quote }}
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: {{ .Values.config.managementEndpointsWebExposureInclude | quote }}
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: {{ .Values.config.managementEndpointHealthProbesEnabled | quote }}
  JAVA_OPTS: {{ .Values.app.javaOpts | quote }}
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.database.ddlAuto | quote }}