apiVersion: batch/v1
kind: Job
metadata:
  name: spring-boot-app-seed
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-boot-app-seed
    spec:
      restartPolicy: Never
      containers:
        - name: seed
          image: ghcr.io/tony-waters/spring-boot-app:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: spring-boot-app-spring-boot-app
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "seed"
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-app-spring-boot-app
                  key: JAVA_OPTS
                  optional: true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password