apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.names.secret }}
  namespace: {{ .Values.namespaces.app }}
type: Opaque
stringData:
  postgres-db: "spring_jpa"
  postgres-user: "spring_user"
  postgres-password: "change-me-now"