apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.app }}
  namespace: {{ .Values.namespaces.app }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.names.app }}
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432