apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.names.app }}
  namespace: {{ .Values.namespaces.app }}
spec:
  serviceName: {{ .Values.names.app }}
  podManagementPolicy: Parallel
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.names.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.names.app }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Values.names.app }}
          image: dpage/pgadmin4:9.14
          imagePullPolicy: Always
          env:
            - name: SCRIPT_NAME
              value: /pgadmin
            - name: PGADMIN_DEFAULT_EMAIL
              value: user@somewhere.com
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.names.secret }}
                  key: pgadmin-password
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: pgadmin-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
              readOnly: true
            - name: {{ .Values.names.volumeClaim }}
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-config
          configMap:
            name: {{ .Values.names.config }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.names.volumeClaim }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi