apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  serviceName: pgadmin
  podManagementPolicy: Parallel
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      terminationGracePeriodSeconds: 10
{{/*      securityContext:*/}}
{{/*        fsGroup: 5050*/}}
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:9.14
{{/*          securityContext:*/}}
{{/*            runAsUser: 5050*/}}
{{/*            runAsGroup: 5050*/}}
          imagePullPolicy: Always
          env:
            - name: SCRIPT_NAME
              value: /pgadmin
{{/*            - name: PGADMIN_REPLACE_SERVERS_ON_STARTUP*/}}
{{/*              value: "True"*/}}
            - name: PGADMIN_DEFAULT_EMAIL
              value: user@domain.com
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin
                  key: pgadmin-password
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: pgadmin-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
              readOnly: true
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-config
          configMap:
            name: pgadmin
  volumeClaimTemplates:
    - metadata:
        name: pgadmin-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 3Gi
